DROP SCHEMA IF EXISTS ProjetoIntegrador ;
CREATE SCHEMA IF NOT EXISTS ProjetoIntegrador DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ProjetoIntegrador ;

CREATE TABLE Pessoa (
	 CPF VARCHAR(15) PRIMARY KEY,
	 SENHA VARCHAR(20) NOT NULL,
	 NOME VARCHAR(50) NOT NULL,
	 GENERO VARCHAR(20) NOT NULL,
	 TIPO_SANG VARCHAR(3) NOT NULL,
	 NUM_EMER VARCHAR(17) NOT NULL,
	 created_at timestamp default now());

CREATE TABLE Sintoma (

	 Num_sintoma serial PRIMARY KEY,
	 CPF VARCHAR(50) NOT NULL,
	 SINTOMA_TITLE VARCHAR(30) DEFAULT NULL,
	 SINTOMA_DESC text NOT NULL ,
	 SINTOMA_DATA DATE NOT NULL ,
	 SINTOMA_PHOTO text DEFAULT NULL , 
	 CONSTRAINT fk_Sintoma_Pessoa1 FOREIGN KEY (CPF) REFERENCES Pessoa (CPF) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE Tratamento (

	 Num_tratamento serial PRIMARY KEY,
	 CPF VARCHAR(50) NOT NULL,
	 TRATAMENTO_TITLE VARCHAR(30) DEFAULT NULL ,
	 TRATAMENTO_DESC text NOT NULL ,
	 TRATAMENTO_DATA DATE NOT NULL ,
	 EXAME_PHOTO text DEFAULT NULL ,
	 RECEITA_PHOTO text DEFAULT NULL ,
	 PRESCRICAO_PHOTO text DEFAULT NULL ,
	 CONSTRAINT fk_Tratamento_Pessoa1 FOREIGN KEY (CPF) REFERENCES Pessoa (CPF) ON DELETE NO ACTION ON UPDATE NO ACTION);